#!/usr/bin/env python3
"""Build a keyed citation registry from the source-library TSV.

Reads the master library (exported from the Drive spreadsheet) and assigns each
entry a stable, human-readable citation key (bibkey). The registry is the single
source of truth that per-repo SOURCES.md files point at by key, so URLs and
descriptions live in exactly one place and never drift.

Output: registry.yaml  (and registry.json for machine use)

Key design:
  - keys are slugified from the entry name, deduped with a -2/-3 suffix
  - keys are STABLE: once shipped, a key must never change (repos cite it).
    Re-running appends/updates fields but preserves existing key->url bindings
    via the optional --lock file.
"""
import csv
import json
import re
import sys
import argparse
from pathlib import Path

STOP = {"the", "a", "an", "of", "and", "for", "to", "with", "in", "on"}


def slug(name: str) -> str:
    # Drop par?>enthetical asides and author-attribution after em dash for the key stem.
    stem = re.split(r"[—–\-]{1,2}|\(", name)[0]
    stem = stem.lower()
    stem = re.sub(r"[^a-z0-9]+", " ", stem).strip()
    words = [w for w in stem.split() if w not in STOP]
    if not words:
        words = re.sub(r"[^a-z0-9]+", " ", name.lower()).split()
    return "-".join(words[:3]) or "ref"


def load(tsv_path: Path):
    with tsv_path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def disambig_token(row):
    """Pick a meaningful word to distinguish two entries sharing a key stem.

    Prefer a distinctive word from the entry title (e.g. an author surname),
    then a tag, then a word from the description. Numbers are a last resort.
    """
    # words from the title after the first em dash / paren — often the author
    after = re.split(r"[—–]", row["entry"])
    pool = []
    if len(after) > 1:
        pool += re.findall(r"[A-Za-z]+", after[1])
    pool += re.findall(r"[A-Za-z]+", row["entry"])
    pool += [t.strip() for t in row["tags"].split(";") if t.strip()]
    pool += re.findall(r"[A-Za-z]+", row["description"])[:6]
    for w in pool:
        w = w.lower()
        if len(w) >= 4 and w not in STOP:
            return w
    return None


def build(rows):
    seen = {}
    entries = []
    for r in rows:
        base = slug(r["entry"])
        key = base
        if key in seen:
            tok = disambig_token(r)
            if tok and f"{base}-{tok}" not in seen:
                key = f"{base}-{tok}"
            else:
                n = 2
                while key in seen:
                    key = f"{base}-{n}"
                    n += 1
        seen[key] = True
        tags = [t.strip() for t in r["tags"].split(";") if t.strip()]
        instruments = [i.strip() for i in r.get("instruments", "").split(";") if i.strip()]
        entries.append({
            "key": key,
            "title": r["entry"].strip(),
            "url": r["url"].strip(),
            "bucket": r["bucket"].strip(),
            "section": r["section"].strip(),
            "section_title": r["section_title"].strip(),
            "tags": tags,
            "priority": "high" if r["priority"].strip() == "star" else "normal",
            "license": r["license"].strip(),
            "description": r["description"].strip(),
            # instruments: filled in by the instrument-tagging pass. Empty = not yet mapped.
            "instruments": instruments,
        })
    return entries


def to_yaml(entries) -> str:
    # Minimal hand-rolled YAML so the script has zero dependencies.
    def esc(s):
        s = str(s)
        if s == "":
            return '""'
        if re.search(r'[:#\[\]{}",&*?|<>=!%@`]', s) or s.strip() != s:
            return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
        return s

    out = ["# Citation registry — generated by build_registry.py",
           "# Stable keys: never rename a key once a repo cites it.",
           "version: 1",
           "entries:"]
    for e in entries:
        out.append(f"  - key: {esc(e['key'])}")
        out.append(f"    title: {esc(e['title'])}")
        out.append(f"    url: {esc(e['url'])}")
        out.append(f"    bucket: {esc(e['bucket'])}")
        out.append(f"    section: {esc(e['section'])}")
        out.append(f"    section_title: {esc(e['section_title'])}")
        tg = ", ".join(esc(t) for t in e["tags"])
        out.append(f"    tags: [{tg}]")
        out.append(f"    priority: {esc(e['priority'])}")
        out.append(f"    license: {esc(e['license'])}")
        out.append(f"    description: {esc(e['description'])}")
        inst = ", ".join(esc(i) for i in e["instruments"])
        out.append(f"    instruments: [{inst}]")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=Path)
    ap.add_argument("--out", type=Path, default=Path("registry.yaml"))
    args = ap.parse_args()
    rows = load(args.tsv)
    entries = build(rows)
    args.out.write_text(to_yaml(entries), encoding="utf-8")
    args.out.with_suffix(".json").write_text(
        json.dumps({"version": 1, "entries": entries}, indent=2), encoding="utf-8")
    # Quick integrity report
    keys = [e["key"] for e in entries]
    assert len(keys) == len(set(keys)), "duplicate keys!"
    print(f"{len(entries)} entries -> {args.out} and {args.out.with_suffix('.json')}")
    print(f"unique keys: {len(set(keys))}")
    print("sample:", ", ".join(keys[:6]))


if __name__ == "__main__":
    main()
