#!/usr/bin/env python3
"""Build a one-page printable songsheet PDF.

Layout (top to bottom):
  - Title (Fraunces, 24pt) + subtitle (Inter, 12pt)
  - Tempo, key, instrument
  - Engraved staff (from tune.svg)
  - Fingering strip (from tune-fingering.svg)
  - Practice tip (from notes.md)
  - Footer with Heifer Zephyr wordmark + sheet-music skill credit

Two backends:
  - Adobe Creative Cloud Claude connector (preferred when --via adobe)
    See references/adobe-handoff.md.
  - ReportLab (default fallback) — works everywhere Python runs.

Usage:
    python build_songsheet_pdf.py \\
        --tune-dir learn-to-play/01-easy/twinkle-twinkle/ \\
        --instrument naf-6hole \\
        --out learn-to-play/01-easy/twinkle-twinkle/tune.pdf

    python build_songsheet_pdf.py --tune-dir <dir> --via adobe ...
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def load_practice_tip(notes_md: Path) -> str:
    if not notes_md.exists():
        return ""
    text = notes_md.read_text()
    m = re.search(r"##\s*Practice tip[^\n]*\n+(.+?)(?:\n##|\Z)",
                  text, re.S | re.I)
    if m:
        return m.group(1).strip()
    # Fallback: any line starting with "Practice"
    for line in text.splitlines():
        if line.lower().startswith("practice"):
            return line.strip()
    return ""


def get_abc_headers(abc_path: Path) -> dict:
    if not abc_path.exists():
        return {}
    headers: dict[str, str] = {}
    for line in abc_path.read_text().splitlines():
        if len(line) > 1 and line[1] == ":":
            headers.setdefault(line[0], line[2:].strip())
        else:
            break  # past header block
    return headers


def reportlab_pdf(out: Path, ctx: dict) -> bool:
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.pdfgen import canvas
        from reportlab.graphics import renderPDF
        from reportlab.graphics.shapes import Drawing
    except ImportError:
        return False

    c = canvas.Canvas(str(out), pagesize=letter)
    page_w, page_h = letter

    # Title
    c.setFont("Helvetica-Bold", 22)
    c.drawString(0.75 * inch, page_h - 1.0 * inch, ctx.get("title", "Untitled"))

    # Subtitle
    c.setFont("Helvetica", 11)
    sub = f"Arranged for {ctx.get('instrument_display','?')}"
    c.drawString(0.75 * inch, page_h - 1.3 * inch, sub)

    # Meta line
    c.setFont("Helvetica-Oblique", 10)
    meta = (
        f"Key: {ctx.get('key', '?')}    "
        f"Meter: {ctx.get('meter', '?')}    "
        f"Tempo: {ctx.get('tempo', '?')}"
    )
    c.drawString(0.75 * inch, page_h - 1.5 * inch, meta)

    # Notation block placeholder (we don't embed SVG inline in this fallback)
    c.setStrokeColorRGB(0.3, 0.3, 0.3)
    c.rect(0.75 * inch, page_h - 5.0 * inch, page_w - 1.5 * inch, 3.0 * inch)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(0.85 * inch, page_h - 1.85 * inch,
                 "(Engraved notation: open tune.svg or tune.ly to view; "
                 "see references/adobe-handoff.md for inline embedding.)")

    # Fingering placeholder
    c.rect(0.75 * inch, page_h - 7.5 * inch, page_w - 1.5 * inch, 2.0 * inch)
    c.drawString(0.85 * inch, page_h - 5.4 * inch,
                 "(Fingering chart: see tune-fingering.svg.)")

    # Practice tip
    c.setFont("Helvetica-Bold", 10)
    c.drawString(0.75 * inch, 1.5 * inch, "Practice tip")
    c.setFont("Helvetica", 9)
    tip = ctx.get("practice_tip", "Take it slow. Find the breath points first.")
    text = c.beginText(0.75 * inch, 1.3 * inch)
    text.setFont("Helvetica", 9)
    for line in tip.splitlines() or [tip]:
        text.textLine(line[:120])
    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(0.75 * inch, 0.6 * inch,
                 "Generated by sheet-music · github.com/tonykoop/sheet-music · MIT license")
    c.showPage()
    c.save()
    return out.exists()


def adobe_handoff(out: Path, ctx: dict, tune_dir: Path) -> bool:
    """Stub for the Adobe MCP path. Returns False (not implemented yet)."""
    print("  Adobe MCP path not implemented in this script (v0.1).")
    print("  See references/adobe-handoff.md for the spec to invoke")
    print("  document_render_layout from a Cowork conversation.")
    return False


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--tune-dir", required=True, type=Path,
                   help="folder containing tune.abc and rendered assets")
    p.add_argument("--instrument", required=True)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--via", default="reportlab",
                   choices=["reportlab", "adobe"],
                   help="rendering backend (default: reportlab)")
    args = p.parse_args()

    tune_dir = args.tune_dir
    if not tune_dir.exists():
        sys.exit(f"missing tune dir: {tune_dir}")

    abc_headers = get_abc_headers(tune_dir / "tune.abc")
    ctx = {
        "title": abc_headers.get("T", "Untitled"),
        "instrument_id": args.instrument,
        "instrument_display": args.instrument,  # registry lookup could pretty this up
        "key": abc_headers.get("K", "?"),
        "meter": abc_headers.get("M", "?"),
        "tempo": abc_headers.get("Q", "?"),
        "practice_tip": load_practice_tip(tune_dir / "notes.md"),
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)

    ok = False
    if args.via == "adobe":
        ok = adobe_handoff(args.out, ctx, tune_dir)
        if not ok:
            print("  falling back to ReportLab")
            ok = reportlab_pdf(args.out, ctx)
    else:
        ok = reportlab_pdf(args.out, ctx)
        if not ok:
            sys.exit("ReportLab not installed. pip install reportlab\n"
                     "(or use --via adobe with the Adobe Creative Cloud "
                     "Claude connector available)")

    if ok:
        print(f"  songsheet -> {args.out}")


if __name__ == "__main__":
    main()
