#!/usr/bin/env python3
"""Deposit a starter songbook into a build repo.

Workflow:
  1. Read the instrument's row from instruments/registry.yaml.
  2. Resolve the target build repo path (--target overrides default).
  3. Pick repertoire from catalog/ (3 easy + 2 intermediate + 1 original).
  4. Run scripts/render_pipeline.py on each tune, scoped to this instrument.
  5. Generate combined fingering chart and one-page songsheet.
  6. Write README.md from assets/templates/learn-to-play-README.md.
  7. Append/update a "Learn to play" section in the build repo's main README.

Usage:
    python deposit_songbook.py \\
        --instrument fujara \\
        --target ~/Documents/GitHub/fujara/

If --target is omitted, defaults to ~/Documents/GitHub/<build_repo>/
where build_repo comes from the registry row.

The script does NOT commit or push. Run GitHub Desktop after to review
and commit.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def load_registry_row(instrument_id: str) -> dict | None:
    text = (REPO_ROOT / "instruments" / "registry.yaml").read_text()
    marker = f"id: {instrument_id}"
    if marker not in text:
        return None
    block = text.split(marker, 1)[1].split("- id:", 1)[0]
    row = {"id": instrument_id}
    for line in block.splitlines():
        ln = line.strip()
        if not ln or ln.startswith("#") or ":" not in ln:
            continue
        k, v = ln.split(":", 1)
        v = v.split("#")[0].strip()
        if v in ("|", ""):
            continue
        row[k.strip()] = v.strip("'\"")
    return row


def resolve_target(row: dict, override: Path | None) -> Path:
    if override:
        return override.expanduser().resolve()
    build_repo = row.get("build_repo", "").split("/")[-1]
    if not build_repo:
        sys.exit(f"registry row for {row['id']} has no build_repo")
    return (Path.home() / "Documents" / "GitHub" / build_repo).resolve()


def pick_repertoire(row: dict, catalog: Path) -> dict:
    """Pick 3 easy + 2 intermediate + 1 original tune folders.

    For v0.1 this is a placeholder: it picks the first available tunes
    that fit the instrument's range. Future versions will be smarter
    (cross-tradition variety, ornament pedagogy ladder, etc.).
    """
    pd = catalog / "public-domain"
    orig = catalog / "original"
    pool = sorted(p for p in pd.glob("*/*/") if (p / "tune.abc").exists())
    originals = sorted(o for o in orig.glob("*/") if (o / "tune.abc").exists())

    return {
        "easy": pool[:3],
        "intermediate": pool[3:5],
        "original": originals[:1],
    }


def run_pipeline(tune_dir: Path, instrument_id: str, dest: Path) -> bool:
    cmd = [
        sys.executable, str(REPO_ROOT / "scripts" / "render_pipeline.py"),
        "--tune", str(tune_dir / "tune.abc"),
        "--instrument", instrument_id,
        "--out", str(dest),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(f"  pipeline error for {tune_dir.name}: {proc.stderr.strip()[:200]}")
    return proc.returncode == 0


def write_readme(target: Path, row: dict, picks: dict):
    template = REPO_ROOT / "assets" / "templates" / "learn-to-play-README.md"
    if not template.exists():
        # Inline fallback
        body = (
            f"# learn-to-play / {row.get('display_name', row['id'])}\n\n"
            f"Starter songbook for the {row.get('display_name', row['id'])}, "
            f"generated by the [sheet-music](https://github.com/tonykoop/sheet-music) skill.\n\n"
            f"See `00-warmup-scales/`, `01-easy/`, `02-intermediate/`, "
            f"`03-original/`. The canonical source for every tune is its "
            f"`tune.abc` file; everything else is generated from it.\n"
        )
    else:
        body = template.read_text()
        body = body.replace("{{display_name}}", row.get("display_name", row["id"]))
        body = body.replace("{{instrument_id}}", row["id"])
        body = body.replace("{{build_repo}}",
                            row.get("build_repo", "tonykoop/" + row["id"]))
    (target / "README.md").write_text(body)


def append_to_build_readme(build_root: Path):
    readme = build_root / "README.md"
    section = (
        "\n## Learn to play\n\n"
        "A starter songbook for this instrument lives in "
        "[`learn-to-play/`](learn-to-play/). It includes warmup scales, "
        "three beginner tunes, two intermediate tunes, one original "
        "Heifer Zephyr commission, and a printable one-page songsheet. "
        "Generated by [sheet-music](https://github.com/tonykoop/sheet-music).\n"
    )
    if not readme.exists():
        readme.write_text(f"# {build_root.name}\n{section}")
        return
    current = readme.read_text()
    if "## Learn to play" in current:
        # Replace the existing section
        before, after = current.split("## Learn to play", 1)
        # find next top-level heading or EOF
        rest = after.split("\n## ", 1)
        new = before.rstrip() + section
        if len(rest) > 1:
            new += "\n## " + rest[1]
        readme.write_text(new)
    else:
        readme.write_text(current.rstrip() + section)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--instrument", required=True)
    p.add_argument("--target", type=Path,
                   help="build repo path (default: ~/Documents/GitHub/<build_repo>)")
    p.add_argument("--dry-run", action="store_true",
                   help="report what would happen without writing")
    args = p.parse_args()

    row = load_registry_row(args.instrument)
    if row is None:
        sys.exit(f"unknown instrument: {args.instrument}")

    target = resolve_target(row, args.target)
    if not target.exists():
        sys.exit(f"build repo path does not exist: {target}")

    learn = target / "learn-to-play"
    if args.instrument != target.name:
        # multiple instruments share this repo (e.g. flutes -> naf, pvc)
        learn = target / "learn-to-play" / args.instrument

    print(f"depositing learn-to-play/ for {args.instrument}")
    print(f"  target: {target}")
    print(f"  learn-to-play path: {learn}")
    if args.dry_run:
        print("  [dry-run; not writing]")

    catalog = REPO_ROOT / "catalog"
    picks = pick_repertoire(row, catalog)

    if args.dry_run:
        for tier, tunes in picks.items():
            print(f"  {tier}: {[t.name for t in tunes]}")
        return

    learn.mkdir(parents=True, exist_ok=True)

    # Warmup scales
    scales_dir = learn / "00-warmup-scales"
    scales_dir.mkdir(exist_ok=True)
    subprocess.run([
        sys.executable, str(REPO_ROOT / "scripts" / "generate_scales.py"),
        "--instrument", args.instrument,
        "--out", str(scales_dir / "range-walk.abc"),
    ], check=False)

    # Repertoire
    for tier_name, src_tier_name in [("01-easy", "easy"),
                                       ("02-intermediate", "intermediate"),
                                       ("03-original", "original")]:
        tier_dir = learn / tier_name
        tier_dir.mkdir(exist_ok=True)
        for tune_src in picks[src_tier_name]:
            dest = tier_dir / tune_src.name
            run_pipeline(tune_src, args.instrument, dest)

    # README
    write_readme(learn, row, picks)
    append_to_build_readme(target)

    print(f"  ✓ deposited. Review changes with GitHub Desktop in {target}.")


if __name__ == "__main__":
    main()
