#!/usr/bin/env python3
"""Sweep a closed epic into an Institutional Knowledge retro note.

Refs #240 (Epic #235). When a major epic closes, the Retrospective /
Lessons-Learned agent (`agents/retrospective.md`) needs the raw material to
distill lessons from: the epic's child stories, the commits that referenced it,
and the PR-review history. This script performs that sweep mechanically so the
agent works from gathered evidence instead of memory, and writes a per-epic
retro note into the Institutional Knowledge folder with a backlink to the source
epic for traceability.

Pipeline:
  1. Fetch the epic body and parse its `## Stories` checklist for child issue
     numbers.
  2. Pull each child story's final state + labels (closed-issue evidence).
  3. Collect commits that reference the epic (`git log --grep`).
  4. Collect PR-review comments that reference the epic (`gh search`).
  5. Emit `epic-<N>-sweep.json` (raw evidence) and `epic-<N>-retro.md` (a
     ready-to-fill retro note in the institutional-knowledge entry format, with
     a `Source: epic #N` backlink).

The network/VCS calls are isolated in thin wrappers so the parsing and
note-building logic is unit-testable without a live repo. Lessons are NEVER
auto-appended to the durable aggregate store — the human accepts them first
(house rule: do not auto-mutate the durable layer).

CLI:
    retrospective_sweep.py --epic 254 [--out DIR] [--repo owner/name] [--dry-run]

Exit 0 = swept, 2 = usage/runtime error.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

# `- [ ] #123 - title (sp 5)` / `- [x] #123 ...` — the epic Stories checklist.
STORY_LINE = re.compile(r"^\s*[-*]\s*\[[ xX]\]\s*#(\d+)\b")
# Bare `#123` references elsewhere in the body, as a fallback.
BARE_REF = re.compile(r"(?<![\w/])#(\d+)\b")

DEFAULT_OUT = "plugins/maker/skills/idea-incubator/references/institutional-knowledge"


def parse_story_numbers(epic_body: str) -> list[int]:
    """Extract child story numbers from an epic body, in order, deduped.

    Prefers the `## Stories` checklist; falls back to bare `#N` references if
    no checklist rows are present.
    """
    seen: dict[int, None] = {}
    for line in epic_body.splitlines():
        m = STORY_LINE.match(line)
        if m:
            seen.setdefault(int(m.group(1)), None)
    if seen:
        return list(seen)
    for m in BARE_REF.finditer(epic_body):
        seen.setdefault(int(m.group(1)), None)
    return list(seen)


def note_path(out_dir: Path, epic_num: int) -> Path:
    return out_dir / f"epic-{epic_num}-retro.md"


def sweep_path(out_dir: Path, epic_num: int) -> Path:
    return out_dir / f"epic-{epic_num}-sweep.json"


def build_retro_note(epic_num: int, title: str, sweep: dict) -> str:
    """Render a ready-to-fill retro note in the institutional-knowledge format.

    The note links back to the source epic and pre-fills the evidence the agent
    gathered, leaving the human-distilled lessons as marked TODOs so nothing is
    fabricated.
    """
    stories = sweep.get("stories", [])
    commits = sweep.get("commits", [])
    pr_refs = sweep.get("pr_comments", [])
    closed = [s for s in stories if s.get("state") == "CLOSED" or s.get("state") == "closed"]
    lines = [
        f"# Retrospective: {title} (#{epic_num})",
        "",
        f"_Source: epic #{epic_num} retro. Generated by retrospective_sweep.py._",
        "",
        "## Evidence swept",
        "",
        f"- Child stories: {len(stories)} ({len(closed)} closed).",
        f"- Commits referencing the epic: {len(commits)}.",
        f"- PR/review references: {len(pr_refs)}.",
        "",
        "### Stories",
    ]
    for s in stories:
        labels = ",".join(s.get("labels", []))
        lines.append(f"- #{s['number']} [{s.get('state', '?')}] {s.get('title', '')} ({labels})")
    if not stories:
        lines.append("- (none parsed from the epic body)")
    lines.extend(["", "### Commits"])
    for c in commits[:50]:
        lines.append(f"- {c}")
    if not commits:
        lines.append("- (none found)")
    lines.extend(
        [
            "",
            "## Lessons (human-distilled — fill before accepting)",
            "",
            "<!-- Distill 1-3 transferable lessons from the evidence above, each in the",
            "     institutional-knowledge entry format. Do NOT fabricate; if the sweep is",
            "     thin, say so. Append accepted lessons to the aggregate store by hand. -->",
            "",
            "### <short lesson title>",
            "- **Context:** <when/where this applies>",
            "- **Lesson:** <the transferable takeaway>",
            "- **Applies-to:** <tag>, <tag>",
            f"- **Source:** epic #{epic_num} retro, <YYYY-MM-DD>",
            "",
            "## Backlink",
            "",
            f"- Source epic: #{epic_num}",
        ]
    )
    return "\n".join(lines) + "\n"


# --- thin network/VCS wrappers (mocked in tests) ----------------------------
def _gh_json(args: list[str]) -> object:
    result = subprocess.run(
        ["gh", *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError((result.stderr or "gh failed").strip())
    return json.loads(result.stdout or "null")


def fetch_epic(epic_num: int, repo: str | None) -> dict:
    args = ["issue", "view", str(epic_num), "--json", "title,body"]
    if repo:
        args += ["--repo", repo]
    data = _gh_json(args)
    return {"title": data.get("title", f"epic #{epic_num}"), "body": data.get("body", "")}


def fetch_story(num: int, repo: str | None) -> dict:
    args = ["issue", "view", str(num), "--json", "number,title,state,labels"]
    if repo:
        args += ["--repo", repo]
    try:
        data = _gh_json(args)
    except RuntimeError:
        return {"number": num, "title": "(unavailable)", "state": "unknown", "labels": []}
    return {
        "number": data.get("number", num),
        "title": data.get("title", ""),
        "state": data.get("state", "unknown"),
        "labels": [lbl["name"] for lbl in data.get("labels", []) if isinstance(lbl, dict)],
    }


def fetch_commits(epic_num: int) -> list[str]:
    result = subprocess.run(
        ["git", "log", "--oneline", f"--grep=#{epic_num}\\b", "-E", "--max-count=50"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        return []
    return [ln for ln in result.stdout.splitlines() if ln.strip()]


def fetch_pr_comments(epic_num: int, repo: str | None) -> list[str]:
    args = ["search", "prs", f"#{epic_num}", "--json", "number,title", "--limit", "30"]
    if repo:
        args += ["--repo", repo]
    try:
        data = _gh_json(args)
    except RuntimeError:
        return []
    return [f"PR #{d['number']}: {d.get('title', '')}" for d in (data or [])]


def run_sweep(epic_num: int, repo: str | None) -> tuple[str, dict]:
    epic = fetch_epic(epic_num, repo)
    story_numbers = parse_story_numbers(epic["body"])
    stories = [fetch_story(n, repo) for n in story_numbers]
    sweep = {
        "epic": epic_num,
        "title": epic["title"],
        "stories": stories,
        "commits": fetch_commits(epic_num),
        "pr_comments": fetch_pr_comments(epic_num, repo),
    }
    return epic["title"], sweep


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Sweep a closed epic into a retro note.")
    parser.add_argument("--epic", required=True, type=int, help="Epic issue number.")
    parser.add_argument("--out", default=DEFAULT_OUT, help="Institutional Knowledge folder.")
    parser.add_argument("--repo", default="", help="owner/name (defaults to gh's current repo).")
    parser.add_argument("--dry-run", action="store_true", help="Print the note; do not write files.")
    args = parser.parse_args(argv)

    try:
        title, sweep = run_sweep(args.epic, args.repo or None)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    note = build_retro_note(args.epic, title, sweep)
    if args.dry_run:
        print(note)
        return 0

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    sweep_path(out_dir, args.epic).write_text(
        json.dumps(sweep, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    note_file = note_path(out_dir, args.epic)
    note_file.write_text(note, encoding="utf-8")
    print(note_file.as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
